---
# This will install LM Sensors and `mod` Proxmox to show sensor data for this node

- name: "Install the LM Sensors package"
  become: true
  ansible.builtin.apt:
    name: "lm-sensors"
    state: "present"
    update_cache: "yes"
    force_apt_get: "yes"

- name: "Auto detect sensors"
  become: true
  ansible.builtin.command: sensors-detect --auto  # noqa no-handler
  changed_when: true

# From: https://github.com/Meliox/PVE-mods
- name: "Uninstall 'Mod' Proxmox dashboard GUI'"
  become: true
  ansible.builtin.shell: |
    cd / \
      && wget https://raw.githubusercontent.com/Meliox/PVE-mods/main/pve-mod-gui-sensors.sh \
      && bash pve-mod-gui-sensors.sh uninstall

- name: "Install'Mod' Proxmox dashboard GUI to show sensors'"
  become: true
  expect:
    command: sh -c "cd / bash pve-mod-gui-sensors.sh install"
    responses:
      'Do you wish to display temperatures for all cores [C] or just an average temperature per CPU [a] (note: AMD only supports average)? (C/a):': 'a'
      'Do you wish to display temperatures in degrees Celsius [C] or Fahrenheit [f]?:': 'C'
      'Do you wish to enable system information? (1/2/n):': '1'
    echo: yes
    timeout: 600

- name: "Make a backup from 'Mod' Proxmox dashboard GUI'"
  become: true
  expect:
    command: sh -c "cd / pve-mod-gui-sensors.sh save-sensors-data"
    responses:
      'Do you wish to continue? (y/n):': 'y'
    echo: yes
    timeout: 600