---
# This playbook deploys the whole application stack in this site.
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html


- name: Start Samba on File-Server
  hosts: FileServers

  vars_files:
    - ../../groups_vars/all.yaml
    - vars/all.yaml

#  roles:
#    - role: file-server

  tasks:
    - include_tasks: tasks/start_samba.yaml
      tags: ['samba']

  handlers:
    - import_tasks: handlers/main.yaml
