---
# This playbook deploys the whole application stack in this site.
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html


- name: Get uptime
  gather_facts: true
  hosts: "{{ target}}"
  
  vars_files:
    - ../../groups_vars/all.yaml

#  roles:
#    - role: common

  tasks:
    - include_tasks: tasks/get_uptime.yaml
      tags: ['uptime']