---
# This playbook deploys the whole application stack in this site.
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html


- name: Ansible Inventory info
  hosts: all
  gather_facts: false

  vars_files:
    - ../../groups_vars/all.yaml

#  roles:
#    - role: common

  tasks:
    - include_tasks: tasks/inventory_info.yaml
      tags: ['inventory']