---
# This playbook deploys the whole application stack in this site.
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html


- name: Ping hosts
  gather_facts: true
  hosts: "{{ target}}"

  vars_files:
    - ../../groups_vars/all.yaml

#  roles:
#    - role: common

  tasks:
    - include_tasks: tasks/ping.yaml
      tags: ['ping']