---
# This will configure the default users and user groups for the node

- name: Testing connection to determine correct login details
  ansible.builtin.include_tasks:
    file: sub_tasks/test_connection.yaml


- name: Get distribution facts
  ansible.builtin.include_tasks:
    file: sub_tasks/get_distribution_facts.yaml


- name: Determine 'become_method'
  ansible.builtin.include_tasks:
    file: sub_tasks/determine_become_method.yaml


# ----------------------------------------------------------------------------------
# Create Ansible management user account
# ----------------------------------------------------------------------------------
# Create a Management user which will be used by the Ansible CLI going-forwards specified in `ansible.cfg` as `remote_user`.
- name: Create Management user groups '{{ management_user_groups }}'
  become: true
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ management_user_groups }}"

- name: Create Management user
  become: true
  ansible.builtin.user:
    name: "{{ management_user }}"
    state: present
    password: "{{management_user_password | string | password_hash('sha512')}}"
    shell: /bin/bash
    system: yes             # Defaults to yes
    createhome: yes        # Defaults to yes

- name: Add Management user to groups
  become: true
  user:
    name: '{{ management_user }}'
    groups: "{{ item }}"
    append: yes
  loop: "{{ management_user_groups }}"

- name: Allow management groups to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ item }}"
    line: "%{{ item }} ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
  loop: "{{ management_user_groups }}"

- name: Set Ansible CLI to use the Management user
  set_fact:
    ansible_user: "{{ management_user }}"
    ansible_password: "{{ management_user_password }}"
    ansible_become_password: "{{ management_user_password }}"
    ansible_become_method: sudo
    cacheable: yes
    
- name: Switching Ansible to use `sudo` become_method now the Management User has passwordless sudo
  block:
    - debug:
        msg: "{{ ansible_become_password }}"
    - name: "Set 'ansible_become_method' to `true`"
      set_fact:
        switch_to_sudo_method: true
        cacheable: yes
    - name: Re-run 'Determine 'become_method' task
      ansible.builtin.include_tasks:
        file: sub_tasks/determine_become_method.yaml

- name: Checking the Management user is set as the current user
  command: whoami
  register: whoami
  changed_when: true

- name: Result from checking the Management user being used
  debug: 
    msg: "Current Ansible user {{ whoami.stdout }}"


# ----------------------------------------------------------------------------------
# Create Standard user accounts
# ----------------------------------------------------------------------------------
- name: Create Management user groups '{{ user_groups }}'
  become: true
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ user_groups }}"

- name: Add standard users
  become: true
  ansible.builtin.user:
    name: "{{ item.username }}"
    state: present
    password: "{{item.password | string | password_hash('sha512')}}"
    shell: /bin/bash
    system: yes             # Defaults to yes
    createhome: yes        # Defaults to yes
    groups: "{{ item.group }}"
  loop: "{{ users }}"
