---
# This will install the sudo package for the node

- name: Disable host key checking
  set_fact:
    ansible_host_key_checking: false


- name: Testing connection to determine correct login details
  ansible.builtin.include_tasks:
    file: sub_tasks/test_connection.yaml


- name: Get distribution facts
  ansible.builtin.include_tasks:
    file: sub_tasks/get_distribution_facts.yaml


- name: "Install sudo"
  become: true
  become_method: su
  ansible.builtin.apt:
    name: "sudo"
    state: "present"
    update_cache: "yes"
    force_apt_get: "yes"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Debian-Buster'   # Only for Debian systems - Not installed by default

# Create /etc/sudoers file 
- name: "Create '/etc/sudoers' file"
  become: true
  become_method: su
  ansible.builtin.file:
    path: /etc/sudoerstest
    state: touch
    owner: root
    group: root
    mode: 0440
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Debian-Buster'   # Only for Debian systems - Not installed by default