---
# This will install the sudo package for the node

- name: Disable host key checking
  set_fact:
    ansible_host_key_checking: false


# ----------------------------------------------------------------------------------
# Testing connection to determine correct login details
# ----------------------------------------------------------------------------------
- name: "Test initial connection using logins stored in `ansible.cfg`."
  ping:
  ignore_unreachable: true
  register: "conn"
- block:
  - name: Changing login details - Configure Ansible to use default `user` login details for a 'freshly-installed' system and use default SSH port 22
    set_fact:
      ansible_user: "{{ default_user }}"
      ansible_password: "{{ default_user_password }}"
      ansible_ssh_private_key_file: ''
      ansible_become_password: "{{ default_user_password }}"
      ansible_port: "{{ default_ssh_port }}"
    when: "conn is mapping and conn.unreachable is defined and conn.unreachable"


# ----------------------------------------------------------------------------------
# This will install the sudo package
# ----------------------------------------------------------------------------------
- name: "Install sudo"
  become: true
  become_method: su
  ansible.builtin.apt:
    name: "sudo"
    state: "present"
    force_apt_get: "yes"

# Create /etc/sudoers file 
- name: "Create '/etc/sudoers' file"
  become: true
  become_method: su
  ansible.builtin.file:
    path: /etc/sudoerstest
    state: touch
    owner: root
    group: root
    mode: 0440