---

# - name: Determine 'become_method'
#   ansible.builtin.include_tasks:
#     file: sub_tasks/determine_become_method.yaml


# This will remove the default user from what is defined in `group_var/all.yaml`

# ----------------------------------------------------------------------------------
# Remove the default user `{{ default_user }}`
# ----------------------------------------------------------------------------------
- name: Remove the default user "{{ default_user }}"
  become: true
  ansible.builtin.user:
    name: "{{ default_user }}"
    state: absent
    remove: yes
    force: yes
  ignore_errors: true

- name: Remove the default user home directory
  become: true
  ansible.builtin.file:
    state: absent
    path: "/home/{{ default_user }}/"
  ignore_errors: true


# ----------------------------------------------------------------------------------
# Allow login as root
# ----------------------------------------------------------------------------------
- name: Force allow logins as root via SSH
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: yes
  notify: 
    - restart ssh

- name: "Force all notified handlers to run at this point, not waiting for normal sync points"
  ansible.builtin.meta: flush_handlers