---
# This playbook deploys the whole application stack in this site.
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html


- name: Commission Print-Server
  hosts: PrintServers

  vars_files:
    - ../../groups_vars/all.yaml
    - vars/all.yaml

 #  roles:
#    - role: print-server

  tasks:
    - include_tasks: tasks/install_cups.yaml
      tags: ['cups']
    - include_tasks: tasks/install_printer_specific_files.yaml
      tags: ['printer_specific']
      
  handlers:
    - import_tasks: handlers/main.yaml