---
# This playbook deploys the whole application stack in this site.
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html


- name: Configure hosts
  hosts: baremetal,virtualmachines
  gather_facts: false

  vars_files:
    - ../../groups_vars/all.yaml

#   roles:
#     - role: commissioning

  tasks:
    - include_tasks: tasks/configure_ssh.yaml
      tags: ['ssh']
    - include_tasks: tasks/add_users.yaml
      tags: ['users']
    - include_tasks: tasks/configure_ssh_keys.yaml
      tags: ['ssh']
    - include_tasks: tasks/remove_default_user.yaml
      tags: ['users']
    - include_tasks: tasks/set_hostname.yaml
      tags: ['hostname']
    - include_tasks: tasks/configure_timezone.yaml
      tags: ['timezone']
    - include_tasks: tasks/configure_unattended_upgrades.yaml
      tags: ['security']

  handlers:
    - import_tasks: handlers/main.yaml
