# Set fact for hard disk limit and retireve the disk information
- set_fact:
    mounts: "{{ ansible_mounts }}"
    disk_limit: "90.00" # 90%, Set disk limit percetnage for when a message is shown the disk is almost full


# List the disk usage of all the disks in the system
- debug:
    var: mounts


# See if the hard drive is almost full, disk limit percentage: 90%
- set_fact: mount="{{ mounts | first }}"  # Get the first mount from the list
- set_fact: disk_usage="{{ mount.size_total - mount.size_available }}"
- set_fact: disk_usage_ratio="{{ disk_usage|float / mount.size_total }}"
- set_fact: disk_usage_s="{{ (disk_usage|float / 1000000000) | round(1, 'common') }}GB"
- set_fact: disk_total_s="{{ (mount.size_total / 1000000000) | round(1, 'common') }}GB"
- set_fact: disk_usage_ratio_s="{{ 100 * (disk_usage_ratio|float) | round(1, 'common') }}%"
- set_fact: disk_limit_ratio_s="{{ (disk_limit|float) |round }}%"
                                                                                                                        
- debug:
    msg: "Disk usage {{ disk_usage_s }} of total {{ disk_total_s }} ({{ disk_usage_ratio_s }}) (should be within limit {{ disk_limit_ratio_s }})"

- name:                                                                                                                 
  assert:
    that: disk_usage_ratio_s < disk_limit_ratio_s
    msg: "Disk usage {{ disk_usage_ratio_s }} exceeds {{ disk_limit_ratio_s }}"
  tags: disk
  any_errors_fatal: true
