- set_fact: uptime_seconds="{{ ansible_uptime_seconds }}"
- set_fact: uptime_days="{{ (uptime_seconds|float / 86400) | round(1, 'floor') }}"

- debug:
    msg: "Uptime: {{ uptime_seconds }} seconds (Days: {{ uptime_days }})"
