---
# Inventory info

- name: Print all Ansible info from the Inventory
  debug:
    msg: '{{ hostvars[item] }}'
  loop: "{{ groups['all'] }}"

- name: Print all Ansible hosts IP addresses from the Inventory
  debug:
    msg: '{{ hostvars[item]["ansible_host"] }}'
#    msg: '{{ hostvars[item] }}'
  loop: "{{ groups['all'] }}"