---
# This will ping the host

- name: ICMP Ping on host
  ansible.builtin.command: 'ping -c 2 {{ ansible_host }}'
  ignore_errors: true
  delegate_to: localhost
  register: result

- name: ICMP Results
  debug:
    msg: "{{ result }}"

- name: Ping hosts via Ansible Ping built-in module
  ansible.builtin.ping:

- name: Ansible Ping built-in module results
  ansible.builtin.debug:
    msg: Host returning IP Address {{ ansible_ssh_host }} from Ping