- name: Update the cache. Only if the last one is more than 3600 seconds ago (apt-get update)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade the OS (apt-get dist-upgrade)
  become: true
  apt: 
    upgrade: dist

- debug:
    msg: "NOTE: Now rebooting the machine as distribution has been updated"

- name: Rebooting machine
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 300
    msg: "Rebooting machine in 5 seconds"
    # reboot_timeout: 3600