- name: Update apt-get repo and cache
  become: true
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all apt packages
  become: true
  apt: 
    upgrade: dist

- debug:
    msg: "NOTE: Now rebooting the machine as packages have been updated"

- name: Rebooting machine
  become: true
  become_method: su
  ansible.builtin.reboot:
    reboot_timeout: 300
    msg: "Rebooting machine in 5 seconds"
    # reboot_timeout: 3600