---
# Get distribution facts
# This is a `sub_task` as it's used more than once

- name: Gather the distribution fact
  setup:

- name: Show gathered distribution
  debug:
    msg: "{{ ansible_facts }}"