---
# Set custom become method
# This is a `sub_task` as it's used more than once

- name: "Set 'become_method' if Ubuntu distribution"
  set_fact:
    custom_become_method: sudo
    cacheable: yes
  when: ansible_distribution == 'Ubuntu'  # Only for Ubuntu systems

- name: "Set 'become_method' if Debian distribution"
  set_fact:
    custom_become_method: su
    cacheable: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Debian-Buster'   # Only for Debian systems