---
# This playbook deploys the whole application stack in this site.
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html


- name: Commission Network-Controller-Server
  hosts: NetworkControllerServers

  vars_files:
    - ../../groups_vars/all.yaml
    - vars/all.yaml
    
#  roles:
#    - role: network-controller-server

  tasks:
    - include_tasks: tasks/install_unifi_network_server.yaml
      tags: ['unifi']
    
  handlers:
    - import_tasks: handlers/main.yaml