---
# This will install Jellyfin

# This will setup the required packages for Jellyfin

# Add the user with a primary group
- name: Create group for Jellyfin
  become: true
  ansible.builtin.group:
    name: "{{ jellyfin_group }}"
    state: present

# Add the user with a primary group
- name: Create user for Jellyfin
  become: true
  ansible.builtin.user:
    name: "{{ jellyfin_user }}"
    comment: "{{ jellyfin_service }} user"
    state: present
    group: "{{ jellyfin_group }}"
    shell: /bin/bash
    system: yes
    createhome: yes
    
- name: Create Media directory
  become: true
  file:
    state: directory
    path: "{{ jellyfin_media_root }}"
    owner: "{{ jellyfin_user }}"
    group: "{{ jellyfin_group }}"
    mode: '0755'

- name: Install Jellyfin
  become: true
  expect:
    command: sh -c "curl https://repo.jellyfin.org/install-debuntu.sh | sudo bash"
    responses:
      'If this looks correct, press <Enter> now to continue installing Jellyfin. ': 'Y'
    echo: yes
    timeout: 600
  register: jellyfin_install
  notify:
    - restart jellyfin

- name: Result from Jellyfin install
  debug: 
    msg: "{{ jellyfin_install.stdout }}"

- name: "Force all notified handlers to run at this point, not waiting for normal sync points"
  ansible.builtin.meta: flush_handlers