---
# This playbook deploys the whole application stack in this site.
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html


- name: Commission NVR-Server
  hosts: NvrServers

  vars_files:
    - ../../groups_vars/all.yaml
    - vars/all.yaml

  roles:
    - role: tigattack.frigate_docker      # Install: https://github.com/tigattack/ansible-role-frigate-docker?tab=readme-ov-file#example-playbooks
      become: true
      vars:
        frigate_docker_config:
          mqtt:
            enabled: true
          detect:
            enabled: false
          record:
            enabled: true
            retain:
              days: 10
              mode: all
            events:
              retain:
                default: 30
                mode: motion
          cameras:
            "IP-DOORBELL-FRONT":
              enabled: true
              ffmpeg:
                inputs:
                  - path: rtsp://admin:5cv6z3d29s@10.0.20.105:554
                    roles:
                      - record
            "IP-CAM-FRONT":
              enabled: true
              ffmpeg:
                inputs:
                  - path: rtsp://u82946431:AF2bgX43dy@10.0.20.101:554/s0
                    roles:
                      - record
            "IP-CAM-REAR":
              enabled: true
              ffmpeg:
                inputs:
                  - path: rtsp://u7598642:6RTvJzwE9Y@10.0.20.102:554/s0
                    roles:
                      - record
            "IP-CAM-SIDE-LEFT":
              enabled: false
              ffmpeg:
                inputs:
                  - path: rtsp://u4486654:SkN6HGfaRs@10.0.20.103:554/s0
                    roles:
                      - record
            "IP-CAM-SIDE-RIGHT":
              enabled: false
              ffmpeg:
                inputs:
                  - path: rtsp://u9875621:DXV9B7z6jK@10.0.20.104:554/s0
                    roles:
                      - record
            "IP-CAM-WIFI":
              enabled: false
              ffmpeg:
                inputs:
                  - path: rtsp://u8273:ieYWSh23@10.0.20.100:554/videoMain
                    roles:
                      - record
        frigate_docker_privileged: true
        frigate_docker_storage_use_docker_volume: false
        frigate_docker_storage_bind_path: "{{ frigate_media_root }}"

  pre_tasks:
    - include_tasks: tasks/setup_drive_mounts.yaml
      tags: ['mounts']
    - include_tasks: tasks/pre_tasks.yaml
      tags: ['frigate']

  tasks:
    - include_tasks: tasks/frigate_admin_logins.yaml
      tags: ['frigate']

  handlers:
    - import_tasks: handlers/main.yaml
