---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: start jellyfin
  service:
    name: "{{ jellyfin_service }}"
    state: started

- name: stop jellyfin
  service:
    name: "{{ jellyfin_service }}"
    state: stopped

- name: restart jellyfin
  ansible.builtin.service:
    name: "{{ jellyfin_service }}"
    state: restarted