---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: stop unifi
  ansible.builtin.systemd_service:
    name: "{{ unifi_service }}"
    state: stopped

- name: start unifi
  ansible.builtin.systemd_service:
    name: "{{ unifi_service }}"
    state: started

- name: restart unifi
  ansible.builtin.systemd_service:
    name: "{{ unifi_service }}"
    state: restarted

- name: status unifi
  ansible.builtin.systemd_service:
    name: "{{ unifi_service }}"
    state: status