---
# This will install CUPS

- name: Update apt-get repo and cache
  become: true
  apt: update_cache=yes cache_valid_time=3600

- name: Install Cups and Samba-related packages
  become: true
  apt:
    name:
      - printer-driver-escpr
      - samba
      - samba-common
      - make
      - sudo
      - whois
      - usbutils
      - build-essential
      - libcups2-dev
      - cups
      - cups-client
      - cups-bsd
      - cups-filters
      - foomatic-db-compressed-ppds
      #- printer-driver-all
      - openprinting-ppds
      - smbclient
      - printer-driver-cups-pdf
      - unzip
    state: present
    update_cache: yes
  notify: restart cups

- name: "Force all notified handlers to run at this point, not waiting for normal sync points"
  ansible.builtin.meta: flush_handlers