---
# Mount Point Root paths
drive_mount_root: "/datastore"    # Drives should be mounted in this folder

# List of drives to mount. These drives should be assigned to this host from the hypervisor.
drive_mounts:
  # Mount the "shared" share from `file-server` and mount to `/datastore/mediadata`
  - name: "//10.0.10.103/nasdata/shared"
    mount_path: "{{ drive_mount_root }}/mediadata/"
    file_system_type: "cifs"
    options: 'username=system,password=kVR91uFaf0'
    state: mounted
    mount_on_boot: true
    format_drive: false


# Shared media locations with disk from Hypervisor
jellyfin_media_root: "{{ drive_mount_root }}/mediadata/"

# Jellyfin service
jellyfin_service: jellyfin

# Jellyfin system user details
jellyfin_user: jellyfin
jellyfin_group: jellyfin