---
# List of Proxmox enterprise repos
enterprise_repos:
  - "deb https://enterprise.proxmox.com/debian {{ ansible_distribution_release }} pve-enterprise"
  - "deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise"
  - "deb https://enterprise.proxmox.com/debian/ceph-quincy {{ ansible_distribution_release }} enterprise"

# List of Proxmox free repos
free_repos:
  - "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"

# PVE Repo signing key
repo_key: "http://download.proxmox.com/debian/proxmox-release-{{ ansible_distribution_release }}.gpg"

# Remove nag screens in Proxmox
remove_nag_screens: true