---
# List of Proxmox enterprise repos
enterprise_repos:
  - "deb https://enterprise.proxmox.com/debian {{ ansible_distribution_release }} pve-enterprise"
  - "deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise"
  - "deb https://enterprise.proxmox.com/debian/ceph-quincy {{ ansible_distribution_release }} enterprise"

# List of Proxmox free repos
free_repos:
  - "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"

# PVE Repo signing key
repo_key: "http://download.proxmox.com/debian/proxmox-release-{{ ansible_distribution_release }}.gpg"

# Remove nag screens in Proxmox
remove_nag_screens: true

# For the PVE Backup Cronjob
backup_destination: "/mnt/pve/nas-host01-backup"    # `backup` SMB Share on `nas-host01`
backup_max: 5
backup_opt_folder: false
backup_healthchecksio: 0  # `0` = False, `1` = True. Should `https://healthchecks.io/` be used?
backup_healthchecksio_url: "https://hc-ping.com/your_uuid_here"