---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: start samba
  service:
    name: "{{ samba_service }}"
    state: started

- name: stop samba
  service:
    name: "{{ samba_service }}"
    state: stopped

- name: restart samba
  service:
    name: "{{ samba_service }}"
    state: restarted