---
# This playbook deploys the whole application stack in this site.
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html


- name: Configure Proxmox Hypervisors
  hosts: hypervisors

  vars_files:
    - ../../groups_vars/all.yaml
    - vars/all.yaml
    
#  roles:
#    - role: hypervisor

  tasks:
    - include_tasks: tasks/configure_repos.yaml
      tags: ['repos']
    - include_tasks: tasks/configure_nag_screen.yaml
      tags: ['nag_screen']