---
# This will install UniFI Network Controller

# This will setup the required packages for UniFi
# Installs with the easy install script from https://community.ui.com/questions/UniFi-Installation-Scripts-or-UniFi-Easy-Update-Script-or-UniFi-Lets-Encrypt-or-UniFi-Easy-Encrypt-/ccbc7530-dd61-40a7-82ec-22b17f027776

- name: Install required pre-prerequisite packages
  become: true
  ansible.builtin.apt:
    name:
      - gnupg
      - curl
      - ca-certificates
      - apt-transport-https
    state: present
    update_cache: yes

- name: Download the easy install script
  become: true
  shell: curl -O https://get.glennr.nl/unifi/install/install_latest/unifi-latest.sh

- name: Install latest Unifi Network Server with the easy install script
  become: true
  shell: |
    yes | bash unifi-latest.sh --skip --fqdn {{ (hostname_prefix + inventory_hostname + hostname_suffix + hostname_domain) }} --email {{ admin_email }}
  register: unifi_install
  notify:
    - restart unifi

- name: Result from Unifi Network Server install
  debug: 
    msg: "{{ unifi_install.stdout }}"

- name: "Force all notified handlers to run at this point, not waiting for normal sync points"
  ansible.builtin.meta: flush_handlers