---
# This will setup the required packages for Emby

# Add the user with a primary group
- name: Create group for Frigate
  become: true
  ansible.builtin.group:
    name: "{{ frigate_group }}"
    state: present

# Add the user with a primary group
- name: Create user for Frigate
  become: true
  ansible.builtin.user:
    name: "{{ frigate_user }}"
    comment: "Frigate user"
    state: present
    group: "{{ frigate_group }}"
    shell: /bin/bash
    system: yes
    createhome: no
    
- name: Create Frigate Media root directory
  become: true
  file:
    state: directory
    path: "{{ frigate_media_root }}"
    owner: "{{ frigate_user }}"
    group: "{{ frigate_group }}"
    mode: '0755'

- name: Install packages
  become: true
  apt:
    name:
      - docker.io
    state: present
    update_cache: yes