---
# This playbook deploys the whole application stack in this site.
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html


- name: Configure Web-Server
  hosts: WebServers

  vars_files:
    - ../../groups_vars/all.yaml
    - vars/all.yaml
    
 #  roles:
 #    - role: web-server

  tasks:
    - include_tasks: tasks/configure_nginx.yaml
      tags: ['nginx']
    - include_tasks: tasks/configure_default_vhost_web_root.yaml
      tags: ['nginx']
    - include_tasks: tasks/configure_php.yaml
      tags: ['php']
    - include_tasks: tasks/update_default_vhost_web_root_files.yaml
      tags: ['nginx']
    - include_tasks: tasks/configure_cronjob.yaml
      tags: ['cron']
      
  handlers:
    - import_tasks: handlers/main.yaml