---
# This playbook deploys the whole application stack in this site.
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html


- name: Stop PHP on Web-Server
  hosts: WebServers

  vars_files:
    - ../../groups_vars/all.yaml
    - vars/all.yaml

#  roles:
#    - role: web-server

  tasks:
    - include_tasks: tasks/stop_php.yaml
      tags: ['php']

  handlers:
    - import_tasks: handlers/main.yaml
